In [3]:
# import numpy 
import numpy as np


In [2]:
# Creating Numpy Array from Python List
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [4]:
a1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
a1.shape

(2, 3)

In [5]:
a1.ndim

2

In [6]:
a1.dtype

dtype('int32')

In [7]:
a1.size

6

In [ ]:
# Creating Numpy Array by Built-in Function
# zero, ones, arange, linspace


In [5]:
np.zeros([2, 4], dtype = 'int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
np.ones([3, 5], dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.full((3, 6), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9, 6.9]])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
###'Random'
# seed
np.random.seed(0)
np.random.random((4, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [15]:
np.random.normal(0, 1, (4, 4))

array([[ 0.44386323,  0.33367433,  1.49407907, -0.20515826],
       [ 0.3130677 , -0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877]])

In [18]:
np.random.randint(0, 10, size = (4, 4))

array([[0, 1, 2, 4],
       [2, 0, 3, 2],
       [0, 7, 5, 9],
       [0, 2, 7, 2]])

In [17]:
np.random.rand(4, 4)

array([[0.03842543, 0.63427406, 0.95894927, 0.65279032],
       [0.63505887, 0.99529957, 0.58185033, 0.41436859],
       [0.4746975 , 0.6235101 , 0.33800761, 0.67475232],
       [0.31720174, 0.77834548, 0.94957105, 0.66252687]])

In [23]:
# Array Indexing and Slicing
x1 = np.random.randint(0, 20, size = 6)
x1

array([10, 11,  8, 11,  2, 19])

In [26]:
x1[4], x1[0], x1[-1]

(2, 10, 19)

In [28]:
#multi - dimensional array 
x2 = np.random.randint(0, 10, size = (3, 4))
x2

array([[2, 0, 8, 8],
       [3, 8, 2, 8],
       [4, 3, 0, 4]])

In [29]:
x2[1][2], x2[0][0]

(2, 2)

In [31]:
x2[1][1] = 1000
x2

array([[   2,    0,    8,    8],
       [   3, 1000,    2,    8],
       [   4,    3,    0,    4]])

In [32]:
# Slicing
x1

array([10, 11,  8, 11,  2, 19])

In [33]:
x1[0:3]

array([10, 11,  8])

In [34]:
x1[::2]

array([10,  8,  2])

In [35]:
x2

array([[   2,    0,    8,    8],
       [   3, 1000,    2,    8],
       [   4,    3,    0,    4]])

In [36]:
x2[:2, :3]

array([[   2,    0,    8],
       [   3, 1000,    2]])

In [37]:
x2[:2,:]

array([[   2,    0,    8,    8],
       [   3, 1000,    2,    8]])

In [38]:
# Reshaping of Array and Transpose
grid = np.arange(1, 10)
grid.shape

(9,)

In [39]:
grid.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
# Array Concatenation and Splitting
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [46]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate((grid, grid)) # axis = 0 by default concatenate by rows

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [48]:
#vstack
x = np.array([[1, 2, 3],
              [2, 3, 4]])
y = np.array([7, 8, 9])
np.vstack((x, y))

array([[1, 2, 3],
       [2, 3, 4],
       [7, 8, 9]])

In [50]:
#hstack
x = np.array([[99],
              [99]])

np.hstack((x, grid))

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

In [54]:
# Splitting Array
x = np.array([1, 2, 3, 4, 5, 6])
x1, x2, x3 = np.split(x, [3, 5])
x1

array([1, 2, 3])

In [55]:
x2

array([4, 5])

In [56]:
x3

array([6])

In [62]:
# Broadcasting and Vectorized operations
a = np.array([1, 2, 3])
a + 5 # Broadcasting

array([6, 7, 8])

In [58]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
a.shape

(4,)

In [63]:
a + b

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [64]:
a * b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [66]:
c = np.arange(3).reshape((3, 1))
c

array([[0],
       [1],
       [2]])

In [68]:
a + c

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [69]:
# Manipulating and Comparing Array
#Aggregation
list_number = [1, 2, 3]
ll = np.array(list_number)

In [70]:
ll

array([1, 2, 3])

In [71]:
sum(ll) # Python sum()

6

In [72]:
np.sum(ll) # NumPy sum()

6

In [73]:
# Create massive array Numpy array
massive_array =np.random.random(10000)
massive_array[:5]

array([0.97857093, 0.11620191, 0.7670237 , 0.41182014, 0.67543908])

In [74]:
massive_array.size

10000

In [75]:
massive_array.shape

(10000,)

In [76]:
%timeit sum(massive_array) # Python built-in function sum()
%timeit np.sum(massive_array) 


1.8 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
16.5 µs ± 6.51 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [77]:
# Standard Deviation and Variance
x = [600, 470, 170, 430, 300]
np.std(x)


147.32277488562318

In [78]:
np.var(x)

21704.0

In [80]:
# Sorting Array
x = np.array([1, 3, 5, 2, 6])
np.sort(x)

array([1, 2, 3, 5, 6])

In [81]:
# a relate function is argsort(), return the index of sorted element
np.argsort(x)

array([0, 3, 1, 2, 4], dtype=int64)

In [83]:
# Sorting along rows and columns
np.random.seed(42)
MatA =np.random.randint(0, 10, (4, 6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [84]:
np.sort(MatA, axis = 0) # axis  = 0 sort columns

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [85]:
np.sort(MatA, axis  = 1) # axis = 1 sort rows

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [86]:
# Linear Algebra
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[4, 5],
              [3, 2],
              [9, 10]])
# A (3 x 3) * B (3 x 2) = C (3 x 2)
A.dot(B) # product

array([[ 37,  39],
       [ 85,  90],
       [133, 141]])

In [87]:
A @ B

array([[ 37,  39],
       [ 85,  90],
       [133, 141]])

In [92]:
# Example :
# Number of jar sold
np.random.seed(0)
sale_amounts = np.random.randint(20, size = (5, 3))

In [89]:
# Create weekly sales
import pandas as pd


In [93]:
weekly_sale = pd.DataFrame(sale_amounts, index = ['Mon', 'Tue', 'Wed', 'Thurs', 'Fri'],
                           columns = ['Chicken', 'Beef', 'Meat'])
weekly_sale

Chicken  Beef  Meat
Mon         12    15     0
Tue          3     3     7
Wed          9    19    18
Thurs        4     6    12
Fri          1     6     7

In [95]:
#create price array
prices = np.array([10, 8, 12])
food_price = pd.DataFrame(prices.reshape(1, 3), index = ['Price'], columns=['Chicken', 'Beef', 'Meat'])


In [96]:
food_price

Chicken  Beef  Meat
Price       10     8    12

In [97]:
weekly_sale.shape, food_price.shape

((5, 3), (1, 3))

In [98]:
total_price = weekly_sale.dot(food_price.T)

In [99]:
total_price

Price
Mon      240
Tue      138
Wed      458
Thurs    232
Fri      142

In [100]:
weekly_sale['total_price'] = total_price

In [101]:
weekly_sale

Chicken  Beef  Meat  total_price
Mon         12    15     0          240
Tue          3     3     7          138
Wed          9    19    18          458
Thurs        4     6    12          232
Fri          1     6     7          142